name: CI/CD Pipeline for Selenium Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: C:/Users/runneradmin/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the project
      - name: Build with Gradle
        run: gradle build

      # Step 5: Run Selenium Tests
      - name: Run Tests
        run: gradle clean test --daemon

      # Step 6: Install Allure CLI via npm
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # Step 7: Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate build/allure-results --clean -o allure-report
          dir allure-report

      # Step 8: Move Allure Report to GitHub Pages folder
      - name: Move Allure Report to Public Folder
        shell: bash
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          mkdir -p public/reports/$timestamp
          mv allure-report/* public/reports/$timestamp/
          echo "REPORT_LINK=https://mamun104.github.io/ci-cd-playwright/reports/$timestamp/index.html" >> $GITHUB_ENV

      # Step 9: Verify directory structure
      - name: List public folder
        shell: bash
        run: ls -R public/reports

      # Step 10: Deploy Allure Report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          keep_files: true

      # Step 11: Send Email with Allure Report Link
      - name: Send Email with Allure Report Link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          from: ${{ secrets.USERNAME }}
          to: mamunur.rashid@byslglobal.com
          subject: "Submission of Automated Selenium Testing Report for Your Review"
          body: |
            Dear Sir,

            I hope this message finds you well.

            I am pleased to share that the Selenium testing has been successfully completed, and the report has been generated using Allure Reporter.
            You may review the detailed findings at your convenience via the link below:

            ${{ env.REPORT_LINK }}

            Kindly let me know if you have any feedback or require further clarification on any specific areas.

            Thank you for your time and consideration.
