name: CI/CD Pipeline for Selenium Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Linux runner

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install Playwright dependencies
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff2-1 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libavif16 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libgles2-mesa \
            libx264-160 \
            flite \
            flite-usenglish

      # Build & Run Tests using Gradle Wrapper
      - name: Build & Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean test

      # Upload Selenium HTML Report to Server
      - name: Upload HTML Test Report
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "build/reports/tests/test/packages/*"
          target: "/var/www/smartpeople-automation-report/"
          port: 22
