name: CI/CD Pipeline for Selenium Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.gradle\caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build & Run Tests
      - name: Build & Run Tests
        run: gradle clean test

      # Upload HTML Test Report as artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: build/reports/tests/test/packages

      # Send Test Report via Email
      - name: Send HTML Report via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}   # Your email
          password: ${{ secrets.EMAIL_PASSWORD }}   # App password or actual password
          subject: "Selenium Test Report"
          body: "Hi,\n\nPlease find the attached Selenium test report.\n\nRegards"
          to: mamunur.rashid@byslglobal.com
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: build/reports/tests/test/packages/testrunner.html
          secure: true
